name: Continuous Delivery with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    - name: Push Docker Image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_USERNAME }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push my-docker-image

    - name: Deploy to Production
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@production-server "docker pull my-docker-image:latest"
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@production-server "docker stop my-docker-container || true"
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@production-server "docker rm my-docker-container || true"
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@production-server "docker run -d --name my-docker-container -p 80:80 my-docker-image:latest"
